#!/bin/bash

# base dir for backlight class
basedir="/sys/class/backlight/"

# get the backlight handler
handler=$basedir$(ls $basedir)"/"

# get current brightness
old_brightness=$(cat $handler"brightness")

# get max brightness
max_brightness=$(cat $handler"max_brightness")

# get current brightness %
old_brightness_p=$(( 100 * $old_brightness / $max_brightness ))

printf $old_brightness_p'%%'

case $BLOCK_BUTTON in
  3) /usr/bin/i3_toggle_brightness.sh ;;
  4) sudo /usr/bin/i3_brightness.sh +2 ;; # scroll up, increase
  5) sudo /usr/bin/i3_brightness.sh -2 ;; # scroll down, decrease
esac
