#!/bin/bash

old_brightness=$(xbacklight -get)

#printf %.0f'%%' $old_brightness

echo "${old_brightness%%.*}%"

case $BLOCK_BUTTON in
  3) /usr/share/i3blocks/i3_brightness_toggle.sh ;;
  4) xbacklight -inc 1;; # scroll up, increase
  5) xbacklight -dec 1 ;; # scroll down, decrease
esac
